server:
  port: 8888
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/native-file-repo
        git:
          uri: https://github.com/dddanglee/spring-cloud-config
          # uri: file:///Users/leesanghyun/git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh

